### ISSUE TITLE
Design / Draw enemies in .PNG format

### ISSUE THREAD

**Issue by alexandraanei** [alexandraanei/2D-Shooter#5]
Suggestion: you can draw the sprites using Piskel.

https://www.piskelapp.com/
@grigoreclara @pandeladonna

**Comment by grigoreclara** [comment]
![CalugarAntiglont_0](https://user-images.githubusercontent.com/37940085/80316504-f502bc80-8806-11ea-92d9-5cd3caa00aeb.png)
![CalugarAntiglont_1](https://user-images.githubusercontent.com/37940085/80316506-f59b5300-8806-11ea-8c49-cb9b9687b282.png)
![CalugarAntiglont_2](https://user-images.githubusercontent.com/37940085/80316507-f633e980-8806-11ea-8084-afb885e15164.png)
![Ghost_0](https://user-images.githubusercontent.com/37940085/80316512-fd5af780-8806-11ea-86d9-05bc3910e309.png)
![Ghost_1](https://user-images.githubusercontent.com/37940085/80316513-fdf38e00-8806-11ea-84f1-291d91aef3bd.png)
![Ghost_2](https://user-images.githubusercontent.com/37940085/80316514-fe8c2480-8806-11ea-8608-5dea263134f9.png)
![Soldier_0](https://user-images.githubusercontent.com/37940085/80316516-05b33280-8807-11ea-94d4-7435af9563ab.png)
![Soldier_1](https://user-images.githubusercontent.com/37940085/80316517-064bc900-8807-11ea-9190-ee36eda69b78.png)
![Soldier_2](https://user-images.githubusercontent.com/37940085/80316518-06e45f80-8807-11ea-9e96-583e1b73df04.png)
![Soldier_3](https://user-images.githubusercontent.com/37940085/80316519-077cf600-8807-11ea-8f11-3e6091a33b23.png)
![FlamingSkeltal](https://user-images.githubusercontent.com/37940085/80316527-106dc780-8807-11ea-9e77-1b6af67db598.gif)
![Skeltal](https://user-images.githubusercontent.com/37940085/80316528-11065e00-8807-11ea-899c-ab7bd98d5f5c.gif)
![SpikeSprite](https://user-images.githubusercontent.com/37940085/80316530-11065e00-8807-11ea-9375-4f521dd19c9e.png)
![Taur](https://user-images.githubusercontent.com/37940085/80316531-119ef480-8807-11ea-8d4a-ad538f3de2ee.png)

**Comment by grigoreclara** [comment]
![SpikeSprite](https://user-images.githubusercontent.com/37940085/80316552-3004f000-8807-11ea-866b-d08355c4f406.png)
![Taur](https://user-images.githubusercontent.com/37940085/80316554-31361d00-8807-11ea-946b-e5eecd051454.png)
![Soldier_3](https://user-images.githubusercontent.com/37940085/80316562-3bf0b200-8807-11ea-91a0-9c84b578a312.png)
![Soldier_0](https://user-images.githubusercontent.com/37940085/80316565-3c894880-8807-11ea-8a93-801783e7b5c6.png)
![Soldier_1](https://user-images.githubusercontent.com/37940085/80316566-3d21df00-8807-11ea-8bfa-fc2e4ae0788c.png)
![Ghost_0](https://user-images.githubusercontent.com/37940085/80316573-41e69300-8807-11ea-8574-74fac717c8bf.png)
![Ghost_1](https://user-images.githubusercontent.com/37940085/80316574-427f2980-8807-11ea-9ebf-a371dbc7cd0f.png)
![Ghost_2](https://user-images.githubusercontent.com/37940085/80316575-4317c000-8807-11ea-8e91-f9390e45d60e.png)
![CalugarAntiglont_1](https://user-images.githubusercontent.com/37940085/80316582-47dc7400-8807-11ea-894e-85fa9bfc313a.png)
![CalugarAntiglont_2](https://user-images.githubusercontent.com/37940085/80316584-48750a80-8807-11ea-8b51-55f56dd29f52.png)
![Uploading CalugarAntiglont_0.png…]()

**Comment by grigoreclara** [comment]
![CalugarAntiglont_2](https://user-images.githubusercontent.com/37940085/80316682-dd780380-8807-11ea-894d-f774f929cafa.png)
![CalugarAntiglont_0](https://user-images.githubusercontent.com/37940085/80316683-de109a00-8807-11ea-833b-5120cd603e43.png)
![CalugarAntiglont_1](https://user-images.githubusercontent.com/37940085/80316684-dea93080-8807-11ea-8cc5-f542d82dc92d.png)
![Ghost_0](https://user-images.githubusercontent.com/37940085/80316689-e5d03e80-8807-11ea-8b41-c5806a2a1945.png)
![Ghost_1](https://user-images.githubusercontent.com/37940085/80316690-e668d500-8807-11ea-805d-2151a0df5a04.png)
![Ghost_2](https://user-images.githubusercontent.com/37940085/80316691-e668d500-8807-11ea-90eb-8c0e738c01cc.png)
![Soldier_2](https://user-images.githubusercontent.com/37940085/80316693-ebc61f80-8807-11ea-98bc-164e928a26fc.png)
![Soldier_3](https://user-images.githubusercontent.com/37940085/80316694-ec5eb600-8807-11ea-90d5-9c76841dc77c.png)
![Soldier_0](https://user-images.githubusercontent.com/37940085/80316695-ec5eb600-8807-11ea-9888-f0cfbed4e621.png)
![Soldier_1](https://user-images.githubusercontent.com/37940085/80316696-ecf74c80-8807-11ea-9e77-0adc1bec5f1c.png)

**Comment by grigoreclara** [comment]
![Soldier_0](https://user-images.githubusercontent.com/37940085/80316764-51b2a700-8808-11ea-964b-42709994b2b1.png)
![Ghost_0](https://user-images.githubusercontent.com/37940085/80316772-58d9b500-8808-11ea-95bf-187e73c9349e.png)
![CalugarAntiglont_2](https://user-images.githubusercontent.com/37940085/80316774-6131f000-8808-11ea-9107-b7fea755563e.png)
![skeletor_0](https://user-images.githubusercontent.com/37940085/80316789-77d84700-8808-11ea-8b6a-1afeea722be1.png)
